Получение данных из форм
htmlacademy-php/1295213-yeticave-12 pull request #11
Opened 2021-10-11 15:18 UTC by EduardKichigin

…ботает, данные с формы в базу не уходят, изображение не сохраняется, не могу найти ошибок

---
:mortar_board: [Получение данных из форм](https://up.htmlacademy.ru/php/12/user/1295213/tasks/13)

2021-10-12 00:57 UTC, b1rdex requested changes

2021-10-12 00:57 UTC, b1rdex commented on index.php
> +$lot_content = include_template('controlles/lot.php', ['rows' => $rows, 'lots' => $lots]);
такого файла нет

2021-10-12 00:57 UTC, b1rdex commented on templates/layout.php
> +            <a class="main-header__add-lot button" href="templates/add-lot.php">Добавить лот</a>
в templates/ должны быть только шаблоны
Тут наверно имелось ввиду /add.php

2021-10-12 00:57 UTC, b1rdex commented on functions.php
> +function validateLength($value, $min, $max) {
Для добавленных функций нужно писать комментарии в phpdoc (это критерий к защите)
И рекомендую ещё добавлять типы аргументов и возвращаемого значения. Это можно делать как в phpdoc, так и нативно

2021-10-12 00:57 UTC, b1rdex commented on templates/add-lot.php
> +<!DOCTYPE html>
В шаблонах страниц не нужно копировать целиком layout. Тут должно быть только содержимое для тега `<main>`, а дальше это нужно передать в шаблон layout.php (как это сделано в index.php)

2021-10-12 00:57 UTC, b1rdex commented on templates/add-lot.php
> +        <form class="form form--add-lot container <?=$classNameForm?>" action="../add.php" method="post" enctype="multipart/form-data"> <!-- form--invalid -->
action можно убрать, тогда форма отправит данные в add.php

2021-10-12 00:57 UTC, b1rdex commented on templates/add-lot.php
> +                    <input id="lot-name" type="text" name="lot-name" placeholder="Введите наименование лота">
Сюда нужно добавить атрибут value и выводить в него данные из $post (не забудь про xss)

2021-10-12 00:57 UTC, b1rdex commented on templates/add-lot.php
> +                    <select id="category" name="category">
1. категории нужно выводить из бд
2. нужно отмечать выбранный элемент из $post

2021-10-12 00:57 UTC, b1rdex commented on templates/add-lot.php
> +                <textarea id="message" name="message" placeholder="Напишите описание лота"><?=getPostVal('message')?></textarea>
xss

2021-10-12 00:57 UTC, b1rdex commented on templates/add-lot.php
> +                    <input id="lot-rate" type="text" name="lot-rate" placeholder="0">
Сюда нужно добавить атрибут value и выводить в него данные из $post (не забудь про xss)

2021-10-12 00:57 UTC, b1rdex commented on templates/add-lot.php
> +                    <input id="lot-step" type="text" name="lot-step" placeholder="0">
Сюда нужно добавить атрибут value и выводить в него данные из $post (не забудь про xss)

2021-10-12 00:57 UTC, b1rdex commented on templates/add-lot.php
> +                    <input class="form__input-date" id="lot-date" type="text" name="lot-date" placeholder="Введите дату в формате ГГГГ-ММ-ДД">
Сюда нужно добавить атрибут value и выводить в него данные из $post (не забудь про xss)

2021-10-12 00:57 UTC, b1rdex commented on add.php
> +    $gif = filter_input_array(INPUT_POST, ['lot-name' => FILTER_DEFAULT, 'category' => FILTER_DEFAULT,
Что означает gif?

2021-10-12 00:57 UTC, b1rdex commented on add.php
> +        'message' => FILTER_DEFAULT, 'lot-rate' => FILTER_DEFAULT, 'lot-step' => FILTER_DEFAULT, 'lot-step' => 'lot-date'], true);
`'lot-step' => 'lot-date'`

тут ошибка

2021-10-12 00:57 UTC, b1rdex commented on add.php
> +//        здесь не понял как записать правильно, в первых скобках наименования соответствуют столбцам в базе, и как установить соединение вообще
Подключения и запросы ты делал в index.php, посмотри там или в lot.php

Подключение к бд лучше вынести в функцию, запросы тоже лушче выносить в отдельные функции

2021-10-13 09:08 UTC, b1rdex requested changes

2021-10-13 09:08 UTC, b1rdex commented on add.php
> +//            по $file_url ошибка, но пробовал ставить '1' вместо, не помогает
$file_url – это сейчас так и идёт в запрос, т.к. он у тебя в одинарных кавычках
Нужно вернуть там ? и добавить эту переменную в массив $lot

2021-10-13 09:08 UTC, b1rdex commented on templates/add-lot.php
> +                    <select id="category" name="category">
Актуально

2021-10-13 09:08 UTC, b1rdex commented on templates/add-lot.php
> +                <textarea id="message" name="message" placeholder="Напишите описание лота"><?=getPostVal('message')?></textarea>
Актуально

2021-10-13 09:08 UTC, b1rdex commented on templates/add-lot.php
> +                    <input class="form__input-date" id="lot-date" type="text" name="lot-date" placeholder="Введите дату в формате ГГГГ-ММ-ДД">
Актуально

2021-10-17 20:50 UTC, hennessyAnn commented
Комменты в ТГ

2021-10-18 15:05 UTC, merged